name: Allaboutme
favicon: null
layout_spectrum: 0.29499
typography_spectrum: 0.21482479479163885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbe3e5'
    - '#1d4072'
    - '#7093c9'
    - '#061903'
    - '#986b50'
  brandStrength: 0.5625
  lightness: 0.23968223948031664
  saturation: 0.6152222268283367
  rhythmicContrast: 0.2566715069115162
purpose: []
